'use client'

import { Card } from "@/components/ui/card"
import { User } from "lucide-react"

const testimonials = [
  {
    name: "Future User",
    role: "Change Management Lead",
    content: "Change Amigo has transformed how we manage organizational change. The AI-driven insights have been invaluable in shaping our strategy and ensuring successful outcomes."
  },
  {
    name: "Potential Client",
    role: "Transformation Director",
    content: "The platform's ability to aggregate and summarize relevant case studies has given us confidence in our change initiatives. It's like having a change management expert at your fingertips."
  },
  {
    name: "Happy Customer",
    role: "Project Manager",
    content: "The insights generated by Change Amigo have helped us anticipate challenges and prepare effectively. It's become an essential tool in our change management toolkit."
  }
]

export function TestimonialCarousel() {
  return (
    <div className="w-full overflow-hidden">
      <div 
        className="flex gap-12 animate-scroll"
      >
        {/* First set */}
        {testimonials.map((testimonial, index) => (
          <Card 
            key={`first-${index}`} 
            className="flex-shrink-0 w-[500px] h-[250px] p-8 transition-all duration-300 hover:bg-emerald-50 hover:transform hover:-translate-y-1 hover:shadow-lg"
          >
            <div className="flex flex-col h-full">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-14 h-14 bg-emerald-100 rounded-full flex items-center justify-center">
                  <User className="w-7 h-7 text-emerald-600" />
                </div>
                <div>
                  <h3 className="font-semibold text-lg">{testimonial.name}</h3>
                  <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                </div>
              </div>
              <div className="flex-1">
                <p className="text-muted-foreground text-base leading-relaxed whitespace-normal">{testimonial.content}</p>
              </div>
            </div>
          </Card>
        ))}
        {/* Second set */}
        {testimonials.map((testimonial, index) => (
          <Card 
            key={`second-${index}`} 
            className="flex-shrink-0 w-[500px] h-[250px] p-8 transition-all duration-300 hover:bg-emerald-50 hover:transform hover:-translate-y-1 hover:shadow-lg"
          >
            <div className="flex flex-col h-full">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-14 h-14 bg-emerald-100 rounded-full flex items-center justify-center">
                  <User className="w-7 h-7 text-emerald-600" />
                </div>
                <div>
                  <h3 className="font-semibold text-lg">{testimonial.name}</h3>
                  <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                </div>
              </div>
              <div className="flex-1">
                <p className="text-muted-foreground text-base leading-relaxed whitespace-normal">{testimonial.content}</p>
              </div>
            </div>
          </Card>
        ))}
      </div>
      <style jsx>{`
        .animate-scroll {
          animation: scroll 20s linear infinite;
        }
        @keyframes scroll {
          from {
            transform: translateX(0);
          }
          to {
            transform: translateX(calc(-50% - 24px));
          }
        }
      `}</style>
    </div>
  )
} 